name: todo_app
description: Todo app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  provider: ^6.0.4
  intl: ^0.17.0
  dio: ^4.0.6
  json_annotation: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.0.0
  build_runner: ^2.0.0
  mockito: ^5.0.0
  mock_web_server: ^5.0.0-nullsafety.1

flutter:
  generate: true
  uses-material-design: true
